### ISSUE TITLE
(NEW) Fix range of slot compound on SolutionComponent

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1666] opened 2024-01-12 23:14 UTC
Discovered while writing ADR

Refer to 
- https://github.com/microbiomedata/NMDC_documentation/pull/36#discussion_r1448131768
- https://github.com/microbiomedata/NMDC_documentation/pull/36#discussion_r1449685590
- https://github.com/microbiomedata/NMDC_documentation/pull/36#discussion_r1449722846
- https://microbiomedata.github.io/berkeley-schema-fy24/SolutionComponent/

 - `Class:Solution` has `slot:has_solution_components` with `Range:Class:SolutionComponent` where `slot:compound` has `Range:Class:ProteolyticEnzymeEnum`.
   -  currently, it's string

**Comment by JamesTessmer** [comment] 2024-01-15 20:26
Update: The enums are being enforced which I confirmed by adding an invalid data file and testing the valid ones with different values. The issue seems to be with the generated documentation saying the range is a string (which is technically true) but it doesn't show the enums being used to enforce the values.

**Comment by mslarae13** [comment] 2024-01-15 21:44
@sujaypatil96  can you help sort out why the generated documentation is wrong? https://microbiomedata.github.io/berkeley-schema-fy24/SolutionComponent/

**Comment by ssarrafan** [comment] 2024-01-22 18:47
> [@sujaypatil96](https://github.com/sujaypatil96) can you help sort out why the generated documentation is wrong? https://microbiomedata.github.io/berkeley-schema-fy24/SolutionComponent/

Should this issue be re-assigned to @sujaypatil96? @mslarae13

**Comment by ssarrafan** [comment] 2024-01-26 22:21
I'm going to remove [this issue](https://github.com/microbiomedata/nmdc-schema/issues/1666) from the sprint and add the backlog label to it.  If it should be active in the next sprint let me know.  If it should be re-assigned to 
[@Sujay Patil](https://nmdc-group.slack.com/team/U02UENGHECD)
 let me know.

**Comment by turbomam** [comment] 2024-01-31 14:37
I would like for us to review the overall modeling of solutions and reagents. The `range` `slot_usage`s for `compound` sound relatively safe to me.

**Comment by turbomam** [comment] 2024-01-31 14:38
see also (eventually!):
- https://github.com/microbiomedata/nmdc-schema/issues/1741

**Comment by anastasiyaprymolenna** [comment] 2024-03-11 20:36
The documentation generation will be resolved with the release of LinkML version 1.7.6, until then the issue will remain open

**Comment by mslarae13** [comment] 2024-03-25 17:51
@anastasiyaprymolenna does this have relevance for the re-working of ChemicalConversionProcess?

**Comment by turbomam** [comment] 2024-03-25 19:08
I'm working on a refactoring of everything solution related for Wednesday

**Comment by turbomam** [comment] 2024-04-02 14:19
`compound` has been replaced by `substances_used`

**Closed by turbomam** 2024-04-02 14:19 UTC
Labels: backlog, chemistry
