### ISSUE TITLE
Create 'shoulder' IDs for the different NMDC minted unique IDs and when/ where to use them

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#370] opened 2022-07-29 23:38 UTC

**Comment by turbomam** [comment] 2022-08-04 01:07
Make it clear which classes are intended to use which shoulders. May require
- a specification within the schema
- query methods in @dwinston's API
- ongoing monitoring

**Comment by ssarrafan** [comment] 2022-09-01 18:30
@mslarae13 moving to Sept but let me know if you're not working on this for the next 2 weeks

**Comment by mslarae13** [comment] 2022-09-09 21:58
Relates to https://github.com/orgs/microbiomedata/projects/34

**Comment by pkalita-lbl** [comment] 2022-09-13 22:08
I'm going to close this issue as a duplicate of https://github.com/microbiomedata/issues/issues/4. This issue may be older, but the other one has more information and is part of the new identifiers squad's project.

**Closed by pkalita-lbl** 2022-09-13 22:08 UTC
Labels: identifiers
