### ISSUE TITLE
update to enforce including id_version in WorkflowExecutionActivity subclasses

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1988] opened 2024-05-17 22:19 UTC
Some NOM workflow execution activity records don't have a ID version and some re-id'd records have multiple workflow ID versions. 
- [x] make example data of valid and invalid data (Alicia) 
- [x] Update the structured_pattern.syntax for WorkflowExeuctionActivity such that the id_version is required.
https://github.com/microbiomedata/nmdc-schema/blob/31522132cf46c50bca1ecb89f563ebf9f366b6ae/src/schema/workflow_execution_activity.yaml#L93
 - [x] update example data as needed
- [x] decide what to do with the current identifiers (ie move ID without ID version to alternative ID slot. alternative_identifiers currently doesn't exist on WorkflowExecutionActivity
- [x] write migrator to implement changes in prod mongo (James) https://github.com/microbiomedata/nmdc-schema/issues/2010
- [x] update berkeley to fix new classes (Katherine)
- [x] Fix read qc and read taxonomy records (Michael) https://github.com/microbiomedata/nmdc_automation/issues/186

**Comment by aclum** [comment] 2024-05-22 22:03
For what to do we decided to add alternative_identifiers to WokflowExecutionActivity subclasses. That PR is https://github.com/microbiomedata/nmdc-schema/pull/1993

**Comment by kheal** [comment] 2024-05-22 23:03
@aclum @turbomam 

Through some testing, I've found that using `"{id_nmdc_prefix}:wfmgan-{id_shoulder}-{id_blade}{id_version}$"` is insufficent for testing _if_ the IDs have a version associated.  

For instance, this test still passes (on my branch) with the id slot usage updated as above:
```
metagenome_annotation_set:
  - id: nmdc:wfmgan-99-4d83z
    type: nmdc:MetagenomeAnnotation
    name: human gut metagenome annotation
    has_input:
      - nmdc:dobj-99-9t74d
    has_output:
      - nmdc:dobj-99-6y6j
    ended_at_time: '2023-08-03T16:00:00Z'
    execution_resource: JGI
    git_url: https://github.com/microbiomedata/metagenome_annotation/releases/tag/v2.5.0
    part_of:
      - nmdc:wfch-99-98f7b
    started_at_time: '2023-08-03T10:00:00Z'
    img_identifiers:
      - img.taxon:2763570002
```

Is this expected behavior?  I would expect we would want the test to fail since the ID does not have a version associated.

**Comment by aclum** [comment] 2024-05-28 23:40
PRs have been merged in to make the workflow IDs pattern matching more stringent and to allow alternative identifiers. This master ticket is expected to span into the next sprint for James' work.

**Comment by aclum** [comment] 2024-06-10 22:23
@kheal  your portion is complete, yes?

**Comment by kheal** [comment] 2024-06-10 22:28
@aclum - Yes, in this PR: https://github.com/microbiomedata/berkeley-schema-fy24/pull/177

**Comment by ssarrafan** [comment] 2024-06-28 21:29
Closing this issue
@aclum

**Closed by ssarrafan** 2024-06-28 21:29 UTC
